# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7330ff23ddb2a7ad613617169b55193cfc7d8d08c5da8f79aa3d7ec4c1a24f162508d69d6d5ad4d0ac07a6db3a3e1bd1ef68d2c52534eecd9f6921c4146944d

test:
  secret_key_base: cf741e4a03ee38f472083805dcd940dbc7cdd42e72414a74d7fac59e157378a0bc3e03e8f2876130d6128de6db6ec577a2318c9e5fcb76dc79eb9363c1de582b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
